name: Single Tenant Net Leased Marketplace
favicon: null
layout_spectrum: 0.46790362033061683
typography_spectrum: 0.2773608367424458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.911652619484812
  lightness: 0.15485580428503454
  saturation: 0.12764165760017931
  rhythmicContrast: 0.38767095166258514
purpose: []
